# Generated by Django 4.2.16 on 2024-12-10 10:31

from django.db import migrations, models
import got.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', got.manager.UserManager()),
            ],
        ),
    ]
